version: "2"

linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - funlen
    - gocheckcompilerdirectives
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godox
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - testifylint
    - unconvert
    - unparam
    - unused
    - whitespace

  settings:
    funlen:
      lines: 100

  exclusions:
    rules:
      - path: (.+)_test.go
        linters:
          - funlen
          - goconst
          - dupl

formatters:
  enable:
    - gofmt
    - goimports
