version: "2"

linters:
  default: none
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - funlen
    - gocheckcompilerdirectives
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godox
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - revive
    - staticcheck
    - testifylint
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    funlen:
      lines: 100
    gosec:
      excludes:
        - G115
        - G117
        - G104
        - G304
    staticcheck:
      checks:
        - "all"
        - "-ST1000"
  exclusions:
    rules:
      - path: (.+)_test.go
        linters:
          - funlen
          - goconst
          - dupl
          - gosec
      - text: "Error return value of `.*Close` is not checked"
        linters:
          - errcheck
      - text: "exported: exported .+ should have comment"
        linters:
          - revive
      - text: "package-comments: should have a package comment"
        linters:
          - revive

formatters:
  enable:
    - gofmt
    - goimports
