{
 "title": "Container Resources",
 "tags": [
  "benchmark",
  "resources",
  "cadvisor"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "containers",
    "label": "Container name regex",
    "query": "postgres|debezium|go-pq-cdc-kafka"
   }
  ]
 },
 "panels": [
  {
   "title": "Container CPU %",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (name) (\n  rate(\n    container_cpu_usage_seconds_total{\n      id!=\"/\",\n      image!=\"\",\n      name=~\"$containers\"\n    }[$__rate_interval]\n  )\n) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Container Memory (Working Set)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name) (\n  container_memory_working_set_bytes{\n    id!=\"/\",\n    image!=\"\",\n    name=~\"$containers\"\n  }\n)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Current CPU %",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (name) (\n  rate(\n    container_cpu_usage_seconds_total{\n      id!=\"/\",\n      image!=\"\",\n      name=~\"$containers\"\n    }[1m]\n  )\n) * 100",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  },
  {
   "title": "Current Memory (Working Set)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (name) (\n  container_memory_working_set_bytes{\n    id!=\"/\",\n    image!=\"\",\n    name=~\"$containers\"\n  }\n)",
     "legendFormat": "{{container_label_com_docker_compose_service}}"
    }
   ]
  }
 ]
}