{
 "title": "Go PQ CDC",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Replication Slots",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "max by (ins, slot_name, datname) (go_pq_cdc_replication_slot_slot_retained_wal_size)"
    },
    {
     "expr": "max by (slot_name) (go_pq_cdc_replication_slot_slot_is_active)"
    },
    {
     "expr": "max by (ins, slot_name, datname) (go_pq_cdc_replication_slot_slot_lag)"
    }
   ]
  },
  { "title": "Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Total Insert Message",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(go_pq_cdc_insert_total[10y])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Update Message",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(go_pq_cdc_update_total[10y])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Delete Message",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(go_pq_cdc_delete_total[10y])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Insert Message",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(go_pq_cdc_insert_total[10y])",
     "legendFormat": "{{slot_name}}"
    }
   ]
  },
  {
   "title": "Update Message",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(go_pq_cdc_update_total[10y])",
     "legendFormat": "{{slot_name}}"
    }
   ]
  },
  {
   "title": "Delete Message",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(go_pq_cdc_delete_total[10y])",
     "legendFormat": "{{slot_name}}"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "go-pq-cdc Latency ",
   "type": "stat",
   "description": "Latency between PostgreSQL message server time and go-pq-cdc consume time",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "go_pq_cdc_cdc_latency_current", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "go-pq-cdc Process Latency ",
   "type": "stat",
   "description": "Handler function process time ",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_pq_cdc_process_latency_current",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}