{
 "title": "Benchmark",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(container_memory_usage_bytes{name=~\"debezium|go-pq-cdc\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\"debezium|go-pq-cdc\"}[$__rate_interval])) by (name) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Received Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=~\"debezium|go-pq-cdc\"}[$__rate_interval])) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sent Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=~\"debezium|go-pq-cdc\"}[$__rate_interval])) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Topic Offset",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "vectorized_cluster_partition_end_offset{topic=\"go-pq-cdc.test.produce\"}",
     "legendFormat": "go-pq-cdc"
    },
    {
     "expr": "vectorized_cluster_partition_end_offset{topic=\"postgres.public.users\"}",
     "legendFormat": "debezium"
    }
   ]
  }
 ]
}