name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    types: [ opened, reopened, synchronize ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  integration_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ "15-alpine",  "15.7-alpine", "16-alpine", "16.3-alpine" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.4'

      - name: Install dependencies
        run: make tidy

      - name: Integration Test
        run: |
          make test/integration
        env:
          POSTGRES_TEST_IMAGE: ${{ matrix.version }}
